workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.tunegocio.app"
    scripts:
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
