workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 60

    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

    scripts:
      - name: Generate Wrapper
        script: |
          gradle wrapper --gradle-version 8.4

      - name: Build Debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
